entities_quick = {
    'abilities': None,
    'addons': None,
    'business_services': None,
    'escalation_policies': None,
    'extension_schemas': None,
    'extensions': None,
    'incidents': None,
    'log_entries': None,
    'maintenance_windows': None,
    'notifications': None,
    'oncalls': None,
    'priorities': None,
    'rulesets': None,
    'schedules': None,
    'services': None,
    'tags': None,
    'teams': None,
    'users/me': None,
    'users': None,
    'vendors': None,
}


entities_full = {
    'abilities': None,
    'addons': ['{entity}/{id}'],
    'business_services': [
        '{entity}/{id}',
        'service_dependencies/{entity}/{id}',
    ],
    'escalation_policies': ['{entity}/{id}'],
    'extension_schemas': ['{entity}/{id}'],
    'extensions': ['{entity}/{id}'],
    'incidents': [
        '{entity}/{id}',
        '{entity}/{id}/alerts',
        '{entity}/{id}/log_entries',
        '{entity}/{id}/notes',
    ],
    'log_entries': ['{entity}/{id}'],
    'maintenance_windows': ['{entity}/{id}'],
    'notifications': None,
    'oncalls': None,
    'priorities': None,
    'rulesets': [
        '{entity}/{id}',
        '{entity}/{id}/rules',
    ],
    'schedules': [
        '{entity}/{id}',
        '{entity}/{id}/overrides',
        '{entity}/{id}/users',
    ],
    'services': [
        '{entity}/{id}',
        'service_dependencies/technical_services/{id}',
    ],
    'tags': [
        '{entity}/{id}',
        '{entity}/{id}/users',
        '{entity}/{id}/teams',
        '{entity}/{id}/escalation_policies',
        '{entity}/{id}/users/tags',
        '{entity}/{id}/teams/tags',
        '{entity}/{id}/escalation_policies/tags',
    ],
    'teams': [
        '{entity}/{id}',
        '{entity}/{id}/members',
    ],
    'users/me': None,
    'users': [
        '{entity}/{id}',
        '{entity}/{id}/sessions',
        '{entity}/{id}/contact_methods',
        '{entity}/{id}/notification_rules',
    ],
    'vendors': ['{entity}/{id}'],
}
